// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: RobotContainer.

package frc.robot;

import edu.wpi.first.wpilibj.GenericHID;
import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import frc.lib.tuneables.TuneablesManager;
import frc.robot.Commands.ShootingCommands;
import frc.robot.POM_lib.Joysticks.PomXboxController;
import frc.robot.Subsystems.shoot.Shoot;

import frc.robot.Commands.DriveCommands;
import frc.robot.POM_lib.Joysticks.PomXboxController;
import frc.robot.Subsystems.drive.Drive;
import frc.robot.Subsystems.drive.DriveIOTalonSRX;
import frc.robot.Subsystems.
Transfer.Transfer;
import frc.robot.Subsystems.Transfer.TransferIOReal;
import frc.robot.Subsystems.NoteIntake.NoteIntake;
import frc.robot.Subsystems.NoteIntake.NoteIntakeIOReal;
import frc.robot.POM_lib.Joysticks.PomXboxController;
import frc.robot.Commands.TransferCommands;
import frc.robot.Commands.NoteIntakeCommands;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 * This class is where the bulk of the robot should be declared. Since
 * Command-based is a
 * "declarative" paradigm, very little robot logic should actually be handled in
 * the {@link Robot}
 * periodic methods (other than the scheduler calls). Instead, the structure of
 * the robot
 * (including subsystems, commands, and button mappings) should be declared
 * here.
 */
public class RobotContainer {
  
  // A chooser for autonomous commands
  SendableChooser<Command> m_chooser = new SendableChooser<>();

  private static RobotContainer m_robotContainer = new RobotContainer();
  
  private final PomXboxController driverController = new PomXboxController(0);
  private final PomXboxController operatorController = new PomXboxController(1);
  private final Drive drive;
  private final Shoot shoot;
  private Transfer transfer;
  private NoteIntake noteIntake;
  
  
  /**
   * The container for the robot. Contains subsystems, OI devices, and commands.
   */
  private RobotContainer() {
    //SmartDashboard.putData("start tune", Commands.runOnce(TuneablesManager::enable));
    noteIntake = new NoteIntake(new NoteIntakeIOReal());
    drive = new Drive(new DriveIOTalonSRX(), null);
    transfer = new Transfer(new TransferIOReal());
    shoot = new Shoot();
    
    configureButtonBindings();

    SmartDashboard.putData("Auto Mode", m_chooser);

    
  }

  public static RobotContainer getInstance() {
    return m_robotContainer;
  }

  /**
   * Use this method to define your button->command mappings. Buttons can be
   * created by
   * instantiating a {@link GenericHID} or one of its subclasses ({@link
   * edu.wpi.first.wpilibj.Joystick} or {@link XboxController}), and then passing
   * it to a
   * {@link edu.wpi.first.wpilibj2.command.button.JoystickButton}.
   */
  private void configureButtonBindings() {

    operatorController.rightTrigger().whileTrue(ShootingCommands.shootNote(shoot, 6));
    operatorController.leftTrigger().whileTrue(TransferCommands.shoot(transfer).alongWith(NoteIntakeCommands.Intake(noteIntake)));
    operatorController.a().onTrue(NoteIntakeCommands.Intake(noteIntake).
    raceWith(TransferCommands.transfer(transfer)));
    drive.setDefaultCommand(DriveCommands.tanckDrive(drive, driverController::getLeftY, driverController::getRightY));
    
    
    operatorController.b().onTrue(NoteIntakeCommands.stop(noteIntake));
    operatorController.x().onTrue(TransferCommands.stop(transfer));
    operatorController.y().onTrue(ShootingCommands.stop(shoot));

    

    // andThen(TransferCommands.shoot(transfer).withTimeout(0.3)).
    // andThen(ShootingCommands.shootNote(shoot).withTimeout(0.5)));

    //operatorController.x().onTrue(ShootingCommands.setSetPointCommand(shoot, 10));


    // operatorController.rightTrigger().whileTrue(ShooterCommands.startEndShoot(shooter, ShooterConstants.SPEED));
    // operatorController.leftTrigger().whileTrue(TransferCommands.shoot(transfer));
    // operatorController.a().onTrue(NoteIntakeCommands.Intake(noteIntake).alongWith(TransferCommands.transfer(transfer)).until(()-> transfer.getTransferSensor()));
    // operatorController.y().onTrue(TransferCommands.stop(transfer).alongWith(NoteIntakeCommands.stop(noteIntake)));
    //operatorController.a().onFalse(TransferCommands.reverseTransfer(transfer).withTimeout(0.25555));
  }

  /**
   * Use this to pass the autonomous command to the main {@link Robot} class.
   *
   * 
   * @return the command to run in autonomous
   */
  public Command getAutonomousCommand() {
    // The selected command will be run in autonomous
    return m_chooser.getSelected();
  }

}
